### ISSUE TITLE
Crash when building the template

### ISSUE THREAD

**Issue by IceReaper** [theolivenbaum/h5#27]
Building on Ubuntu 20.04. Only installed sdk is 3.1

```
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  [info] [16:13:09] Found compilation server
  Running _ComputePackageReferencePublish for Test
  Running _HandlePackageFileConflicts
  Running _ComputeReferenceAssemblies
  Running _ComputeUserRuntimeAssemblies
  Running GenerateBuildDependencyFile
  No output assembly found, will build.
  Running _GenerateRuntimeConfigurationFilesInputCache
  Running GenerateBuildRuntimeConfigurationFiles
  Writing project runtime config file /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.runtimeconfig.json
  Test -> 
  Skipping updating the h5 compiler. You can always install/update it by calling dotnet tool update --global h5-compiler
  Deleting previous assembly: /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.dll
  H5 compilation begins now... 
  
  
  
       5555555555555555555555555555555555555555
        5555555555555555555hhhhhhhhhhhhhhhh5555
        555     55555555555hh             h5555 
        555     55555555555hh             h555  
        555     55555555555hh     hhhhhhhhh555  
         55     55555555555hh     hhhhhhhhh555  
         555     5555555555hh     hhhhhhhh5555  
         555              5hh            h5555  
         555              5hh            h555   
          555    5555     5hhhhhhhh      h555   
          555    5555     5hhhhhhhh      h555   
          555     555     5hhhhhhhh     h5555   
          555     555     5hh           h555    
          5555555 555     5hh        hhhh555    
           5555555555555555hhhhhhhhhhhhhh555    
           5555555555555555hhhhhhh5555555555    
                 55555555555555555555           
                   5555555555555555            
  
  
  [info] [16:13:10] Executing h5 compiler with arguments: '--project /home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj --configuration Debug --assembly-version 1.0.0.0'
  [info] [16:13:10] Found compilation server, sending compilation request
  
  
  [info] [16:13:10]  Setting working directory to '/home/andre/RiderProjects/Tetys/csharp/Test'
  [info] [16:13:10]  [B] H5 Compilation
  [info] [16:13:10]  H5 config file is not found. Returning default config
  [info] [16:13:10]  [E] H5 Compilation in 0.0010 seconds
  [info] [16:13:10]  
  
       __ _  _  _  _ 
      |_ |_)|_)/ \|_)
      |__| \| \\_/| \
  
  
  [fail] [16:13:10]  
H5 : error H5003: The SDK 'h5.Target/0.0.11500' specified could not be found.  /home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj [/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj]
  [fail] [16:13:10]  
  Stack Trace:    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
     at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
     at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
     at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
     at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
     at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
     at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
     at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
     at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
     at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
     at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
     at H5.Translator.Translator.EnsureProjectProperties()
     at H5.Translator.TranslatorProcessor.SetTranslatorProperties()
     at H5.Translator.TranslatorProcessor.PreProcess(IH5DotJson_AssemblySettings translatorConfiguration)
     at H5.Compiler.CompilationProcessor.Compile(CompilationRequest compilationRequest, UID128 compilationUID, CancellationToken cancellationToken)
/home/andre/.nuget/packages/h5.target/0.0.11500/Sdk/Sdk.targets(462,9): error MSB3073: The command "h5 --project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" --configuration "Debug" --assembly-version "1.0.0.0"" exited with code 1. [/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj]

Build FAILED.

H5 : error H5003: The SDK 'h5.Target/0.0.11500' specified could not be found.  /home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj [/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj]
/home/andre/.nuget/packages/h5.target/0.0.11500/Sdk/Sdk.targets(462,9): error MSB3073: The command "h5 --project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" --configuration "Debug" --assembly-version "1.0.0.0"" exited with code 1. [/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.58
```

**Comment by IceReaper** [comment]
Another day, another problem: My machine has rebooted meanwhile, and above error is gone now. So it might be related to leftover .net5 stuff in the os. The compilation itself however still fails with this error:
```
Build started 10/20/2020 10:20:05 AM.
Logging verbosity is set to: Normal.     1>Project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" on node 1 (build target(s)).
     1>_CheckForH5:
         h5 check-if-online
         [info] [10:20:06] Found compilation server
       _ComputePackageReferencePublish:
         Running _ComputePackageReferencePublish for Test
       _HandlePackageFileConflicts:
         Running _HandlePackageFileConflicts
       _ComputeReferenceAssemblies:
         Running _ComputeReferenceAssemblies
       _ComputeUserRuntimeAssemblies:
         Running _ComputeUserRuntimeAssemblies
       GenerateBuildDependencyFile:
         Running GenerateBuildDependencyFile
         No output assembly found, will build.
       _GenerateRuntimeConfigurationFilesInputCache:
         Running _GenerateRuntimeConfigurationFilesInputCache
       GenerateBuildRuntimeConfigurationFiles:
         Running GenerateBuildRuntimeConfigurationFiles
         Writing project runtime config file /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.runtimeconfig.json
       CopyFilesToOutputDirectory:
         Test -> 
       _H5Build:
         Skipping updating the h5 compiler. You can always install/update it by calling dotnet tool update --global h5-compiler
         Deleting previous assembly: /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.dll
         H5 compilation begins now... 
         h5 --project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" --configuration "Debug" --assembly-version "1.0.0.0"
         
         
         
              5555555555555555555555555555555555555555
               5555555555555555555hhhhhhhhhhhhhhhh5555
               555     55555555555hh             h5555 
               555     55555555555hh             h555  
               555     55555555555hh     hhhhhhhhh555  
                55     55555555555hh     hhhhhhhhh555  
                555     5555555555hh     hhhhhhhh5555  
                555              5hh            h5555  
                555              5hh            h555   
                 555    5555     5hhhhhhhh      h555   
                 555    5555     5hhhhhhhh      h555   
                 555     555     5hhhhhhhh     h5555   
                 555     555     5hh           h555    
                 5555555 555     5hh        hhhh555    
                  5555555555555555hhhhhhhhhhhhhh555    
                  5555555555555555hhhhhhh5555555555    
                        55555555555555555555           
                          5555555555555555            
         
         
         [info] [10:20:06] Executing h5 compiler with arguments: '--project /home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj --configuration Debug --assembly-version 1.0.0.0'
         [info] [10:20:06] Found compilation server, sending compilation request
         
         
         [info] [10:20:07]  Setting working directory to '/home/andre/RiderProjects/Tetys/csharp/Test'
         [info] [10:20:07]  [B] H5 Compilation
         [info] [10:20:07]  Ready to build /home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj
         [info] [10:20:07]  [B] Translating assembly
         [info] [10:20:07]  Building assembly on path /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.dll
         [info] [10:20:07]  [B] Building assembly 'Test' for location '/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj'
         [info] [10:20:07]  NuGet: Importing package h5.Core version 0.0.8126
         [info] [10:20:07]  NuGet: Importing package h5 version 0.0.8032
         [info] [10:20:07]  NuGet: Copying lib file '/home/andre/.nuget/packages/h5.core/0.0.8126/lib/netstandard2.0/H5.Core.dll' to '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/H5.Core.dll'
         [info] [10:20:07]  NuGet: Copying lib file '/home/andre/.nuget/packages/h5/0.0.8032/lib/netstandard2.0/H5.dll' to '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/H5.dll'
         [info] [10:20:07]  Loading references from assembly /home/andre/.nuget/packages/h5.core/0.0.8126/lib/netstandard2.0/H5.Core.dll
         [info] [10:20:07]  Loading references from assembly /home/andre/.nuget/packages/h5/0.0.8032/lib/netstandard2.0/H5.dll
         [info] [10:20:07]  [B] Compiling /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.dll with Roslyn
         [info] [10:20:07]  [E] Compiling /home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/Test.dll with Roslyn in 0.0356 seconds
         [info] [10:20:07]  [E] Building assembly 'Test' for location '/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj' in 0.0460 seconds
         [info] [10:20:07]  [B] Inspecting references
         [info] [10:20:07]  [E] Inspecting references in 0.0823 seconds
         [info] [10:20:07]  Running compiler version 0.0.12179:
         [info] [10:20:07]  [B] Rewritting code
         [info] [10:20:07]  [E] Rewritting code in 0.0066 seconds
         [info] [10:20:07]  [B] Building syntax tree
         [info] [10:20:07]  [E] Building syntax tree in 0.0021 seconds
         [info] [10:20:07]  [B] Loading assembly definitions
         [info] [10:20:09]  [E] Loading assembly definitions in 1.3700 seconds at 1 oper/s, total of 2 operations
         [info] [10:20:09]  [B] Inspecting types
         [info] [10:20:09]  [E] Inspecting types in 0.0009 seconds
         [info] [10:20:09]  [B] Creating Emitter
         [info] [10:20:09]  [E] Sorting types by name in 0.0000 seconds
         [info] [10:20:09]  [E] Creating Emitter in 0.1498 seconds
         [info] [10:20:09]  [B] Emitting JavaScript code
         [info] [10:20:10]  [B] Emitting types to javascript
         [info] [10:20:10]  [B] Emitting types reflection metadata to javascript
         [info] [10:20:10]  [E] Emitting types reflection metadata to javascript in 0.0010 seconds
         [info] [10:20:10]  [E] Emitting types to javascript in 0.0871 seconds
         [info] [10:20:10]  [E] Emitting JavaScript code in 0.7711 seconds
         [info] [10:20:10]  [E] Translating assembly in 2.4300 seconds
         [info] [10:20:10]  [B] Post-processing output on '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/' for project '/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj'
         [info] [10:20:10]  [B] Extracting core scripts
         [info] [10:20:10]  [B] Extracting resources
         [info] [10:20:10]  [E] Extracting resources in 0.0197 seconds
         [info] [10:20:10]  Skipping extracting Locales
         [info] [10:20:10]  [E] Extracting core scripts in 0.0197 seconds
         [info] [10:20:11]  [B] Saving results to output folder '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/'
         [info] [10:20:11]  [E] Saving results to output folder '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/' in 0.0060 seconds
         [info] [10:20:11]  [B] Injecting resources from project '/home/andre/RiderProjects/Tetys/csharp/Test' into output '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/'
         [info] [10:20:11]  [E] Injecting resources from project '/home/andre/RiderProjects/Tetys/csharp/Test' into output '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/' in 0.0002 seconds
         [info] [10:20:11]  [E] Post-processing output on '/home/andre/RiderProjects/Tetys/csharp/Test/bin/Debug/netstandard2.0/h5/' for project '/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj' in 1.5000 seconds
         [info] [10:20:11]  [E] H5 Compilation in 4.1400 seconds
         [info] [10:20:11]  
         
              __ _  _  _  _ 
             |_ |_)|_)/ \|_)
             |__| \| \\_/| \
         
         
         [fail] [10:20:11]  
     1>H5 : error H5003: This operation is not supported for a relative URI.
         [fail] [10:20:11]  
         Stack Trace:    at System.Uri.get_LocalPath()
            at H5.Translator.Translator.PrepareAndExtractResources(String outputPath, String projectPath)+MoveNext()
            at H5.Translator.Translator.PrepareResourcesForEmbedding(IEnumerable`1 resourcesToEmbed)
            at H5.Translator.Translator.InjectResources(String outputPath, String projectPath)
            at H5.Translator.TranslatorProcessor.PostProcess()
            at H5.Compiler.CompilationProcessor.Compile(CompilationRequest compilationRequest, UID128 compilationUID, CancellationToken cancellationToken)
     1>/home/andre/.nuget/packages/h5.target/0.0.11500/Sdk/Sdk.targets(462,9): error MSB3073: The command "h5 --project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" --configuration "Debug" --assembly-version "1.0.0.0"" exited with code 1.
     1>Done Building Project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" (build target(s)) -- FAILED.

Build FAILED.

       "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" (build target) (1) ->
       (_H5Build target) -> 
         H5 : error H5003: This operation is not supported for a relative URI.
         /home/andre/.nuget/packages/h5.target/0.0.11500/Sdk/Sdk.targets(462,9): error MSB3073: The command "h5 --project "/home/andre/RiderProjects/Tetys/csharp/Test/Test.csproj" --configuration "Debug" --assembly-version "1.0.0.0"" exited with code 1.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:06.46

```

**Comment by theolivenbaum** [comment]
Interesting, could you share your h5.json and project files?

**Comment by IceReaper** [comment]
h5.json
```
{
  "html": {
    "disabled": false
  }
}
```
Program.cs
```
namespace Test
{
	using H5.Core;

	public class Program
	{
		public static void Main(string[] args)
		{
			dom.document.body.innerText = "Hello World!";
		}
	}
}
```
Test.csproj
```
<Project Sdk="h5.Target/0.0.11500">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="h5" Version="0.0.8032" />
        <PackageReference Include="h5.Core" Version="0.0.8126" />
    </ItemGroup>
</Project>
```

**Comment by theolivenbaum** [comment]
And you're running on linux right?

**Comment by IceReaper** [comment]
Yes, Ubuntu 20.04.

**Comment by theolivenbaum** [comment]
Hi @IceReaper - can you try one thing before I go into the code, just update the packages in your project to the latest:

`````xml
<PackageReference Include="h5" Version="0.0.11453" />
<PackageReference Include="h5.core" Version="0.0.11860" />
`````
I'll update the template project here too with the latest versions - need to automate this on the devops build...

**Comment by theolivenbaum** [comment]
Here is the actual fully updated template: https://github.com/theolivenbaum/h5/blob/master/Template/templates/MyProject.csproj

**Comment by IceReaper** [comment]
Im having the exact same error when using the newer packages :(

**Comment by theolivenbaum** [comment]
Ok thanks for checking. I'll try to reproduce here and let you know what I find

**Comment by theolivenbaum** [comment]
Hi @IceReaper 

Managed to reproduce the problem here on a Linux machine - will test a fix for it now.
Meanwhile, you can set a flag on your project file (SkipEmbeddingResources = true) to get it compiling (just remove it once the fix is done):

`````csproj
<Project Sdk="h5.Target/0.0.11500">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>7.2</LangVersion>
        <SkipEmbeddingResources>true</SkipEmbeddingResources>         <------- this line
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="h5" Version="0.0.11453" />
        <PackageReference Include="h5.core" Version="0.0.11860" />
        <PackageReference Include="h5.Newtonsoft.Json" Version="0.0.11861" />
        <PackageReference Include="Tesserae" Version="0.0.13054" />
    </ItemGroup>
</Project>
`````

**Comment by IceReaper** [comment]
Yup, that prop made it work. Thank you very much :)

**Comment by theolivenbaum** [comment]
@IceReaper can you test the latest version and see if it fixed this?
`dotnet tool update --global h5-compiler --version 0.0.13348`

**Comment by IceReaper** [comment]
I can confirm this is fixed.
